/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export type ConversationControllerGetListConversationsSortDirection =
  (typeof ConversationControllerGetListConversationsSortDirectionConst)[keyof typeof ConversationControllerGetListConversationsSortDirectionConst];

export const ConversationControllerGetListConversationsSortDirectionConst = {
  asc: "asc",
  desc: "desc",
} as const;
