/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export interface ConversationCreateRequestDTO {
  /** The title of the conversation */
  title: string;
  /** The model of the conversation */
  model: string;
  /** The description of the conversation */
  description?: string;
}
