/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export type ConversationControllerGetListConversationsSortDirection =
  (typeof ConversationControllerGetListConversationsSortDirection)[keyof typeof ConversationControllerGetListConversationsSortDirection];

// eslint-disable-next-line no-redeclare
export const ConversationControllerGetListConversationsSortDirection = {
  asc: "asc",
  desc: "desc",
} as const;
