/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export type ConversationControllerGetPinnedConversationsSortDirection =
  (typeof ConversationControllerGetPinnedConversationsSortDirection)[keyof typeof ConversationControllerGetPinnedConversationsSortDirection];

// eslint-disable-next-line no-redeclare
export const ConversationControllerGetPinnedConversationsSortDirection = {
  asc: "asc",
  desc: "desc",
} as const;
