/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export type MessageControllerListMessagesParams = {
/**
 * The page number
 */
page: number;
/**
 * The number of items per page
 */
limit: number;
};
