/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export interface ConversationPinRequestDTO {
	/** Whether the conversation is pinned */
	is_pinned: boolean;
}
