/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */
import type { MessageResponseDTO } from "./messageResponseDTO";

export interface ListMessageResponseDTO {
  /** The messages */
  data: MessageResponseDTO[];
  /** The total number of messages */
  total: number;
}
