/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export type ConversationControllerGetListConversationsSortDirection =
	(typeof ConversationControllerGetListConversationsSortDirectionType)[keyof typeof ConversationControllerGetListConversationsSortDirectionType];

export const ConversationControllerGetListConversationsSortDirectionType = {
	asc: "asc",
	desc: "desc",
} as const;
