/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ConversationResponseDTO } from "./conversationResponseDTO";

export interface ListConversationResponseDTO {
	/** The conversations */
	data: ConversationResponseDTO[];
	/** The total number of conversations */
	total: number;
}
