/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export interface LoginResponseDto {
	/** The access token of the user */
	accessToken: string;
	/** The refresh token of the user */
	refreshToken: string;
	/** Token expire time */
	expiresIn: number;
	/** User's email */
	email: string;
	/** User's username */
	username: string;
	/** User's role */
	role: string;
}
