/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
	/** The email of the user */
	email: string;
	/** The password of the user */
	password: string;
}
