/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export interface MessageDownvoteRequestDTO {
  /** Downvote */
  downvote: boolean;
}
