/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
	/** The email of the user */
	email: string;
	/** The username of the user */
	username: string;
	/** The password of the user */
	password: string;
	/** The first name of the user */
	firstName: string;
	/** The last name of the user */
	lastName: string;
}
