/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export interface SuccessResponse {
	/** The message of the response */
	message: string;
	/** The code of the response */
	code: number;
}
