/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Interstellar API
 * Interstellar API Documentation
 * OpenAPI spec version: 1.0
 */

export interface UserResponseDto {
  /** The ID of the user */
  id: string;
  /** The email of the user */
  email: string;
  /** The username of the user */
  username: string;
  /** The date and time the user was created */
  createdAt: string;
}
